### ISSUE TITLE
Deno should be bundled

### ISSUE THREAD

**Issue by jrmuizel** [mbonig/node-vs-deno#1]
See https://news.ycombinator.com/item?id=23792466

**Comment by jgentil** [comment]
It feels like a really incomplete test if you don't use the most important optimization features of a tool in an optimization/perforamnce test.

**Comment by folkhack** [comment]
It's super disingenuous to ignore the bundling features of Deno in your benchmarks... I believe that anyone developing a solution similar to what you posit in your blog post would be using that feature to speed-up initialization time, *especially* in a production environment.

Please reconsider and revise your post... Deno is an incredibly exciting technology for us JS devs and I don't want to see naive implementations that ignore core features push people away. I'm already seeing your post with 40+ upvotes on HN - this is concerning.

**Comment by mbonig** [comment]
Cold-starts are a well known problem. Yes, bundling would solve that issue and I'll update the repo to bundle. However, that does not invalidate any of the runtime durations I benchmarked as they were always done against warmed lambdas.

I understand everyone at hackernews got all upset that I didn't bundle. I was specific in the blog post about testing against warm lambdas. I'm sorry whoever posted my blog decided to toss ""cold-start" in the title since that's th exact opposite of what I was doing.

**Comment by mbonig** [comment]
Thanks for the feedback everyone! I've updated the original post with some details after bundling the dependencies. Please let me know if I might have bundled them wrong.
